name: Futurerestore

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 1 *'
    - cron: '0 0 1 4 *'
    - cron: '0 0 30 6 *'
    - cron: '0 0 28 9 *'
    - cron: '0 0 27 12 *'

jobs:
  macOS:
    env:
      PROCURSUS: /opt/procursus
      PATH: /opt/procursus/bin:/opt/procursus/libexec/gnubin:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/opt/ruby@2.7/bin:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.7.3/x64
    runs-on: macos-12
    steps:
    - name: Checkout
      id: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'true'
        fetch-depth: 0
    - name: Update Xcode
      id: Update-Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.1.0'
    - name: macOS Build
      id: macOS-Build
      run: |
        ${{ github.workspace }}/.github/workflows/mac-bootstrap.sh
        ${{ github.workspace }}/.github/workflows/mac-build.sh
        ${{ github.workspace }}/.github/workflows/mac-post.sh
    - name: Versioning
      id: Versioning
      uses: actions/upload-artifact@v4
      with:
        name: Versioning
        path: |
          ${{ github.workspace }}/latest_build_sha.txt
          ${{ github.workspace }}/latest_build_num.txt
    - name: macOS RELEASE Archive
      id: macOS-RELEASE-Archive
      uses: actions/upload-artifact@v4
      with:
        name: futurerestore-macOS-RELEASE
        path: |
          ${{ github.workspace }}/futurerestore-macOS-*-RELEASE.tar.xz
    - name: macOS DEBUG Archive
      id: macOS-DEBUG-Archive
      uses: actions/upload-artifact@v4
      with:
        name: futurerestore-macOS-DEBUG
        path: |
          ${{ github.workspace }}/futurerestore-macOS-*-DEBUG.tar.xz
    - name: macOS ASAN Archive
      id: macOS-ASAN-Archive
      uses: actions/upload-artifact@v4
      with:
        name: futurerestore-macOS-ASAN
        path: |
          ${{ github.workspace }}/futurerestore-macOS-*-ASAN.tar.xz
